language: node_js
node_js:
  - 'lts/*'
cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  edge: true
  cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
